/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: famousandfaded (https://sketchfab.com/famousandfaded)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/airports-around-the-world-e58f56a352b540469fd209abf0c37bc5
Title: Airports around the world
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Model =(props) =>{
  const { nodes, materials } = useGLTF('/airports_around_the_world.glb')
  return (
    <group {...props} dispose={null}>
      <group
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.2}
        userData={{ name: 'Airports.obj.cleaner.materialmerger.gles' }}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.matairport_material}
          userData={{ name: 'Object_2' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.matairport_material}
          userData={{ name: 'Object_3' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.matsurface_material}
          userData={{ name: 'Object_4' }}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/airports_around_the_world.glb')

export default Model
