/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: drei.lu (https://sketchfab.com/drei.lu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-exploration-wlp-series-8-91964c1ce1a34c3985b6257441efa500
Title: Space exploration [WLP series #8]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Model=(props) =>{
  const { nodes, materials } = useGLTF('/space_exploration_wlp_series_8.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[0.1, 0.6, 0.5]}
          rotation={[0.238019, -0.5453875, 0.5622766]}
          scale={[1,1, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.planet001_1.geometry}
            material={materials.scene}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.planet001_2.geometry}
            material={materials.scene}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/space_exploration_wlp_series_8.glb')

export default Model